insert into dish (dish_name, price, dish_category, orders) values ('Mishixiang', 29.36, 'BEERS', 16);
insert into dish (dish_name, price, dish_category, orders) values ('Karabudakhkent', 25.48, 'BEERS', 199);
insert into dish (dish_name, price, dish_category, orders) values ('Coratatal', 16.72, 'MAINS', 65);
insert into dish (dish_name, price, dish_category, orders) values ('Shuanglong', 16.29, 'DRINKS', 199);
insert into dish (dish_name, price, dish_category, orders) values ('Bang Racham', 23.5, 'MAINS', 56);
insert into dish (dish_name, price, dish_category, orders) values ('Shiban', 34.7, 'MAINS', 130);
insert into dish (dish_name, price, dish_category, orders) values ('Fengyan', 33.75, 'BEERS', 65);
insert into dish (dish_name, price, dish_category, orders) values ('Zhuji', 18.73, 'DRINKS', 195);
insert into dish (dish_name, price, dish_category, orders) values ('Koźmin Wielkopolski', 29.36, 'MAINS', 75);
insert into dish (dish_name, price, dish_category, orders) values ('Uyuni', 33.15, 'BEERS', 154);
insert into dish (dish_name, price, dish_category, orders) values ('Kozakai-chō', 16.23, 'WINES', 170);
insert into dish (dish_name, price, dish_category, orders) values ('Jiaoshi', 25.72, 'WINES', 126);
insert into dish (dish_name, price, dish_category, orders) values ('Asaka', 25.5, 'ADDONS', 130);
insert into dish (dish_name, price, dish_category, orders) values ('Tsalka', 8.6, 'DRINKS', 137);
insert into dish (dish_name, price, dish_category, orders) values ('Conceição do Araguaia', 18.46, 'MAINS', 141);
insert into dish (dish_name, price, dish_category, orders) values ('Taipingchuan', 17.65, 'WINES', 28);
insert into dish (dish_name, price, dish_category, orders) values ('Shouyan', 22.1, 'PRE', 170);
insert into dish (dish_name, price, dish_category, orders) values ('Novopavlovsk', 26.11, 'ADDONS', 60);
insert into dish (dish_name, price, dish_category, orders) values ('Isheyevka', 33.31, 'MAINS', 173);
insert into dish (dish_name, price, dish_category, orders) values ('Březí', 11.06, 'MAINS', 122);
insert into dish (dish_name, price, dish_category, orders) values ('Daxin', 18.46, 'WINES', 197);
insert into dish (dish_name, price, dish_category, orders) values ('Ganjun', 27.97, 'SNACKS', 133);
insert into dish (dish_name, price, dish_category, orders) values ('Krasnyy Lyman', 24.26, 'PRE', 154);
insert into dish (dish_name, price, dish_category, orders) values ('El Tambo', 10.52, 'MAINS', 87);
insert into dish (dish_name, price, dish_category, orders) values ('Jacksonville', 31.92, 'PRE', 66);
insert into dish (dish_name, price, dish_category, orders) values ('Sujitan', 15.77, 'EXTRA', 116);
insert into dish (dish_name, price, dish_category, orders) values ('Tawangrejo', 24.47, 'MAINS', 197);
insert into dish (dish_name, price, dish_category, orders) values ('Tranås', 29.53, 'PRE', 70);
insert into dish (dish_name, price, dish_category, orders) values ('Viejo Daan Banua', 23.43, 'MAINS', 169);
insert into dish (dish_name, price, dish_category, orders) values ('Loma Alta', 15.49, 'MAINS', 182);
insert into dish (dish_name, price, dish_category, orders) values ('Colorado Springs', 22.45, 'WINES', 115);
insert into dish (dish_name, price, dish_category, orders) values ('Krutja e Poshtme', 24.82, 'PRE', 175);
insert into dish (dish_name, price, dish_category, orders) values ('Lagyná', 34.66, 'DRINKS', 130);
insert into dish (dish_name, price, dish_category, orders) values ('Kimry', 33.94, 'WINES', 90);
insert into dish (dish_name, price, dish_category, orders) values ('Cilimus Kulon', 13.74, 'BEERS', 55);
insert into dish (dish_name, price, dish_category, orders) values ('‘Irbīn', 17.61, 'PRE', 76);
insert into dish (dish_name, price, dish_category, orders) values ('Aduo', 15.41, 'WINES', 28);
insert into dish (dish_name, price, dish_category, orders) values ('Balkanabat', 12.29, 'MAINS', 170);
insert into dish (dish_name, price, dish_category, orders) values ('Burevestnik', 26.29, 'EXTRA', 194);
insert into dish (dish_name, price, dish_category, orders) values ('Biaoshan', 32.23, 'EXTRA', 192);
insert into dish (dish_name, price, dish_category, orders) values ('Tromsø', 20.32, 'WINES', 171);
insert into dish (dish_name, price, dish_category, orders) values ('Cicapar', 29.26, 'PRE', 160);
insert into dish (dish_name, price, dish_category, orders) values ('Gaoguan', 12.91, 'MAINS', 8);
insert into dish (dish_name, price, dish_category, orders) values ('Iporá', 25.05, 'PRE', 54);
insert into dish (dish_name, price, dish_category, orders) values ('Zhangguanying', 24.26, 'MAINS', 42);
insert into dish (dish_name, price, dish_category, orders) values ('Kurmanayevka', 20.14, 'DESSERTS', 108);
insert into dish (dish_name, price, dish_category, orders) values ('Changbai', 21.5, 'MAINS', 42);
insert into dish (dish_name, price, dish_category, orders) values ('Quilmaná', 30.84, 'WINES', 126);
insert into dish (dish_name, price, dish_category, orders) values ('Nagrak', 10.63, 'PRE', 186);
insert into dish (dish_name, price, dish_category, orders) values ('General Enrique Mosconi', 6.4, 'BEERS', 83);
insert into dish (dish_name, price, dish_category, orders) values ('Diadi', 34.46, 'DESSERTS', 106);
insert into dish (dish_name, price, dish_category, orders) values ('El Águila', 19.98, 'WINES', 111);
insert into dish (dish_name, price, dish_category, orders) values ('Velykyy Klyuchiv', 31.09, 'BEERS', 43);
insert into dish (dish_name, price, dish_category, orders) values ('Ljubešćica', 33.19, 'MAINS', 135);
insert into dish (dish_name, price, dish_category, orders) values ('Lesnoye', 25.06, 'MAINS', 51);
insert into dish (dish_name, price, dish_category, orders) values ('Kladruby', 23.35, 'WINES', 140);
insert into dish (dish_name, price, dish_category, orders) values ('Jincheng', 7.3, 'DESSERTS', 32);
insert into dish (dish_name, price, dish_category, orders) values ('Fengyuan', 14.46, 'MAINS', 17);
insert into dish (dish_name, price, dish_category, orders) values ('Imulolong', 7.88, 'DESSERTS', 135);
insert into dish (dish_name, price, dish_category, orders) values ('San Miguel', 17.63, 'PRE', 183);
insert into dish (dish_name, price, dish_category, orders) values ('Smyga', 22.38, 'DRINKS', 102);
insert into dish (dish_name, price, dish_category, orders) values ('Noebesa', 20.67, 'MAINS', 107);
insert into dish (dish_name, price, dish_category, orders) values ('Shangyi', 18.09, 'MAINS', 77);
insert into dish (dish_name, price, dish_category, orders) values ('Yoshii', 34.56, 'MAINS', 24);
insert into dish (dish_name, price, dish_category, orders) values ('Paraipaba', 14.84, 'WINES', 19);
insert into dish (dish_name, price, dish_category, orders) values ('Üydzen', 15.29, 'BEERS', 175);
insert into dish (dish_name, price, dish_category, orders) values ('Igboho', 27.63, 'WINES', 78);
insert into dish (dish_name, price, dish_category, orders) values ('Rungis', 6.28, 'MAINS', 148);
insert into dish (dish_name, price, dish_category, orders) values ('Paris 11', 18.35, 'WINES', 85);
insert into dish (dish_name, price, dish_category, orders) values ('Jaguariúna', 23.76, 'DRINKS', 7);
insert into dish (dish_name, price, dish_category, orders) values ('Duanjia', 30.31, 'BEERS', 95);
insert into dish (dish_name, price, dish_category, orders) values ('Indramayu', 30.66, 'MAINS', 76);
insert into dish (dish_name, price, dish_category, orders) values ('Sagasa', 8.21, 'DRINKS', 157);
insert into dish (dish_name, price, dish_category, orders) values ('Strömstad', 17.25, 'MAINS', 51);
insert into dish (dish_name, price, dish_category, orders) values ('Drayton Valley', 14.77, 'MAINS', 161);
insert into dish (dish_name, price, dish_category, orders) values ('Bích Động', 15.52, 'MAINS', 81);
insert into dish (dish_name, price, dish_category, orders) values ('Veisiejai', 16.59, 'WINES', 11);
insert into dish (dish_name, price, dish_category, orders) values ('Przytyk', 20.03, 'ADDONS', 41);
insert into dish (dish_name, price, dish_category, orders) values ('Sekampung', 34.16, 'PRE', 74);
insert into dish (dish_name, price, dish_category, orders) values ('Nova Russas', 11.71, 'PRE', 112);
insert into dish (dish_name, price, dish_category, orders) values ('Fīrūzābād', 7.37, 'WINES', 192);
insert into dish (dish_name, price, dish_category, orders) values ('Al Khāniq', 11.0, 'MAINS', 65);
insert into dish (dish_name, price, dish_category, orders) values ('Varniai', 28.22, 'ADDONS', 172);
insert into dish (dish_name, price, dish_category, orders) values ('Kafr Kannā', 30.44, 'MAINS', 6);
insert into dish (dish_name, price, dish_category, orders) values ('Lugovskoy', 29.36, 'BEERS', 24);
insert into dish (dish_name, price, dish_category, orders) values ('Saint-Rémi', 34.75, 'WINES', 170);
insert into dish (dish_name, price, dish_category, orders) values ('Suba', 15.13, 'ADDONS', 62);
insert into dish (dish_name, price, dish_category, orders) values ('Liandu', 8.38, 'MAINS', 177);
insert into dish (dish_name, price, dish_category, orders) values ('Bartolomé Masó', 13.35, 'MAINS', 95);
insert into dish (dish_name, price, dish_category, orders) values ('Poá', 9.64, 'WINES', 141);
insert into dish (dish_name, price, dish_category, orders) values ('Artur Nogueira', 20.51, 'DRINKS', 117);
insert into dish (dish_name, price, dish_category, orders) values ('Pingxi', 26.96, 'MAINS', 10);
insert into dish (dish_name, price, dish_category, orders) values ('Deshan', 11.14, 'MAINS', 195);
insert into dish (dish_name, price, dish_category, orders) values ('Kyzylzhar', 19.23, 'ADDONS', 152);
insert into dish (dish_name, price, dish_category, orders) values ('Al ‘Ayzarīyah', 18.32, 'PRE', 22);
insert into dish (dish_name, price, dish_category, orders) values ('Huayuan', 33.66, 'MAINS', 157);
insert into dish (dish_name, price, dish_category, orders) values ('Três Lagoas', 20.74, 'WINES', 74);
insert into dish (dish_name, price, dish_category, orders) values ('Huai’an', 12.15, 'MAINS', 54);
insert into dish (dish_name, price, dish_category, orders) values ('Sinanju', 21.06, 'BEERS', 119);
insert into dish (dish_name, price, dish_category, orders) values ('Pengbu', 31.95, 'MAINS', 59);
insert into dish (dish_name, price, dish_category, orders) values ('Washington', 10.95, 'MAINS', 50);
insert into dish (dish_name, price, dish_category, orders) values ('Vladikavkaz', 27.62, 'MAINS', 135);
insert into dish (dish_name, price, dish_category, orders) values ('Meghrashen', 15.75, 'BEERS', 142);
insert into dish (dish_name, price, dish_category, orders) values ('Ílion', 25.66, 'DRINKS', 159);
insert into dish (dish_name, price, dish_category, orders) values ('Xilai', 6.65, 'MAINS', 196);
insert into dish (dish_name, price, dish_category, orders) values ('Ivanovskoye', 16.56, 'SNACKS', 2);
insert into dish (dish_name, price, dish_category, orders) values ('Šentvid pri Stični', 8.46, 'WINES', 129);
insert into dish (dish_name, price, dish_category, orders) values ('Bantaeng', 9.72, 'MAINS', 93);
insert into dish (dish_name, price, dish_category, orders) values ('Fengren', 28.9, 'DRINKS', 70);
insert into dish (dish_name, price, dish_category, orders) values ('Prusice', 12.94, 'DRINKS', 40);
insert into dish (dish_name, price, dish_category, orders) values ('G‘azalkent', 25.86, 'DRINKS', 123);
insert into dish (dish_name, price, dish_category, orders) values ('Tippi', 21.75, 'MAINS', 191);
insert into dish (dish_name, price, dish_category, orders) values ('Putina', 16.0, 'DESSERTS', 184);
insert into dish (dish_name, price, dish_category, orders) values ('Ostrów Mazowiecka', 12.35, 'PRE', 3);
insert into dish (dish_name, price, dish_category, orders) values ('Culeng', 24.44, 'MAINS', 120);
insert into dish (dish_name, price, dish_category, orders) values ('San Juan del Surutú', 9.9, 'MAINS', 187);
insert into dish (dish_name, price, dish_category, orders) values ('Ad Dann', 6.48, 'PRE', 158);
insert into dish (dish_name, price, dish_category, orders) values ('Södertälje', 21.07, 'BEERS', 54);
insert into dish (dish_name, price, dish_category, orders) values ('La Palma', 7.6, 'WINES', 74);
insert into dish (dish_name, price, dish_category, orders) values ('Seropédica', 12.31, 'BEERS', 45);
insert into dish (dish_name, price, dish_category, orders) values ('Pacapausa', 15.88, 'WINES', 131);
insert into dish (dish_name, price, dish_category, orders) values ('Mahābād', 24.97, 'PRE', 144);
insert into dish (dish_name, price, dish_category, orders) values ('Capitán Sarmiento', 17.32, 'MAINS', 57);
insert into dish (dish_name, price, dish_category, orders) values ('Znamenskoye', 29.26, 'MAINS', 106);
insert into dish (dish_name, price, dish_category, orders) values ('Lamphun', 27.67, 'PRE', 25);
insert into dish (dish_name, price, dish_category, orders) values ('Ciela Lebak', 25.15, 'MAINS', 90);
insert into dish (dish_name, price, dish_category, orders) values ('Hāsilpur', 24.62, 'ADDONS', 43);
insert into dish (dish_name, price, dish_category, orders) values ('Tayabo', 19.29, 'EXTRA', 109);
insert into dish (dish_name, price, dish_category, orders) values ('Chantilly', 17.57, 'MAINS', 28);
insert into dish (dish_name, price, dish_category, orders) values ('Potrerillos', 10.88, 'MAINS', 178);
insert into dish (dish_name, price, dish_category, orders) values ('Tambakrejo', 17.51, 'DESSERTS', 172);
insert into dish (dish_name, price, dish_category, orders) values ('Crauthem', 24.91, 'DESSERTS', 176);
insert into dish (dish_name, price, dish_category, orders) values ('Arcos', 12.01, 'DRINKS', 111);
insert into dish (dish_name, price, dish_category, orders) values ('Al Faḩāḩīl', 26.77, 'EXTRA', 110);
insert into dish (dish_name, price, dish_category, orders) values ('Vlkoš', 31.0, 'WINES', 82);
insert into dish (dish_name, price, dish_category, orders) values ('Yingkeng', 10.86, 'BEERS', 42);
insert into dish (dish_name, price, dish_category, orders) values ('Rimpakgede', 20.47, 'MAINS', 43);
insert into dish (dish_name, price, dish_category, orders) values ('Bojongsarung', 18.59, 'MAINS', 82);
insert into dish (dish_name, price, dish_category, orders) values ('Pulo', 27.11, 'MAINS', 166);
insert into dish (dish_name, price, dish_category, orders) values ('Helmsange', 21.77, 'MAINS', 192);
insert into dish (dish_name, price, dish_category, orders) values ('Čoka', 31.35, 'MAINS', 9);
insert into dish (dish_name, price, dish_category, orders) values ('San Diego', 8.03, 'MAINS', 31);
insert into dish (dish_name, price, dish_category, orders) values ('Nanpiao', 34.94, 'PRE', 131);
insert into dish (dish_name, price, dish_category, orders) values ('Castelões', 14.0, 'DESSERTS', 12);
insert into dish (dish_name, price, dish_category, orders) values ('Cuauhtemoc', 28.73, 'MAINS', 125);
insert into dish (dish_name, price, dish_category, orders) values ('Weston', 7.29, 'ADDONS', 22);
insert into dish (dish_name, price, dish_category, orders) values ('Trois-Rivières', 24.88, 'DESSERTS', 65);
insert into dish (dish_name, price, dish_category, orders) values ('Béziers', 32.7, 'MAINS', 114);
insert into dish (dish_name, price, dish_category, orders) values ('Vir', 21.91, 'ADDONS', 192);
insert into dish (dish_name, price, dish_category, orders) values ('Tondabayashichō', 21.18, 'BEERS', 126);
insert into dish (dish_name, price, dish_category, orders) values ('Mīr Bachah Kōṯ', 7.27, 'MAINS', 115);
insert into dish (dish_name, price, dish_category, orders) values ('Gunajaya', 18.94, 'DRINKS', 72);
insert into dish (dish_name, price, dish_category, orders) values ('Nanyanchuan', 19.71, 'MAINS', 8);
insert into dish (dish_name, price, dish_category, orders) values ('Shahrak-e Bākharz', 20.99, 'PRE', 51);
insert into dish (dish_name, price, dish_category, orders) values ('Denver', 17.12, 'WINES', 3);
insert into dish (dish_name, price, dish_category, orders) values ('Huyuan', 10.26, 'WINES', 82);
insert into dish (dish_name, price, dish_category, orders) values ('Hinthada', 9.78, 'BEERS', 143);
insert into dish (dish_name, price, dish_category, orders) values ('Yidu', 33.52, 'MAINS', 115);
insert into dish (dish_name, price, dish_category, orders) values ('Tucano', 29.33, 'WINES', 40);
insert into dish (dish_name, price, dish_category, orders) values ('Anadia', 22.45, 'WINES', 45);
insert into dish (dish_name, price, dish_category, orders) values ('Detupia', 8.43, 'WINES', 55);
insert into dish (dish_name, price, dish_category, orders) values ('Urrô', 10.58, 'WINES', 145);
insert into dish (dish_name, price, dish_category, orders) values ('Kambing', 34.13, 'MAINS', 138);
insert into dish (dish_name, price, dish_category, orders) values ('Koźmin Wielkopolski', 17.58, 'DRINKS', 163);
insert into dish (dish_name, price, dish_category, orders) values ('Aija', 7.08, 'MAINS', 171);
insert into dish (dish_name, price, dish_category, orders) values ('Xiangzhou', 31.72, 'PRE', 112);
insert into dish (dish_name, price, dish_category, orders) values ('Tekikbanyuurip', 30.27, 'PRE', 190);
insert into dish (dish_name, price, dish_category, orders) values ('Hidalgo', 12.31, 'WINES', 163);
insert into dish (dish_name, price, dish_category, orders) values ('Al Lubban al Gharbī', 27.78, 'DRINKS', 173);
insert into dish (dish_name, price, dish_category, orders) values ('Xintun', 29.29, 'MAINS', 140);
insert into dish (dish_name, price, dish_category, orders) values ('San Antonio', 14.58, 'PRE', 168);
insert into dish (dish_name, price, dish_category, orders) values ('Liwonde', 17.83, 'ADDONS', 113);
insert into dish (dish_name, price, dish_category, orders) values ('Nizhnyaya Tura', 12.65, 'PRE', 77);
insert into dish (dish_name, price, dish_category, orders) values ('Lawepakam', 12.35, 'BEERS', 27);
insert into dish (dish_name, price, dish_category, orders) values ('Kokologo', 29.98, 'MAINS', 177);
insert into dish (dish_name, price, dish_category, orders) values ('Maromitsa', 7.06, 'DRINKS', 123);
insert into dish (dish_name, price, dish_category, orders) values ('Līkak', 30.69, 'EXTRA', 23);
insert into dish (dish_name, price, dish_category, orders) values ('Nova Olímpia', 24.81, 'EXTRA', 176);
insert into dish (dish_name, price, dish_category, orders) values ('Palma De Mallorca', 25.69, 'MAINS', 139);
insert into dish (dish_name, price, dish_category, orders) values ('Bengubelan', 12.45, 'PRE', 29);
insert into dish (dish_name, price, dish_category, orders) values ('Linëvo', 16.09, 'DRINKS', 152);
insert into dish (dish_name, price, dish_category, orders) values ('Sendafa', 10.01, 'MAINS', 8);
insert into dish (dish_name, price, dish_category, orders) values ('Kirovsk', 14.8, 'MAINS', 37);
insert into dish (dish_name, price, dish_category, orders) values ('Vindeln', 32.67, 'DRINKS', 171);
insert into dish (dish_name, price, dish_category, orders) values ('Cimonyong', 8.38, 'DESSERTS', 194);
insert into dish (dish_name, price, dish_category, orders) values ('Palmerston North', 21.01, 'PRE', 166);
insert into dish (dish_name, price, dish_category, orders) values ('Longquan', 30.27, 'SNACKS', 70);
insert into dish (dish_name, price, dish_category, orders) values ('Lewoeleng', 17.98, 'ADDONS', 68);
insert into dish (dish_name, price, dish_category, orders) values ('Vaiusu', 33.5, 'MAINS', 177);
insert into dish (dish_name, price, dish_category, orders) values ('Xinshui', 6.82, 'DRINKS', 150);
insert into dish (dish_name, price, dish_category, orders) values ('Tayu', 24.7, 'DRINKS', 170);
insert into dish (dish_name, price, dish_category, orders) values ('Xinó Neró', 28.51, 'MAINS', 123);
insert into dish (dish_name, price, dish_category, orders) values ('Pindobaçu', 8.38, 'DESSERTS', 75);
insert into dish (dish_name, price, dish_category, orders) values ('Créteil', 22.74, 'EXTRA', 132);
insert into dish (dish_name, price, dish_category, orders) values ('Kanginan', 7.35, 'MAINS', 48);
insert into dish (dish_name, price, dish_category, orders) values ('Waingapu', 11.27, 'MAINS', 196);
insert into dish (dish_name, price, dish_category, orders) values ('Paris 08', 15.84, 'WINES', 124);
insert into dish (dish_name, price, dish_category, orders) values ('Malway', 26.56, 'MAINS', 25);
insert into dish (dish_name, price, dish_category, orders) values ('Francisco I Madero', 11.65, 'MAINS', 185);
insert into dish (dish_name, price, dish_category, orders) values ('Beihe', 14.66, 'DRINKS', 185);
